2022-08-04T05:50:35.5576122+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-04T05:50:35.5824101+08:00|10|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-04T05:50:35.6359779+08:00|10|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-04T05:50:35.6890504+08:00|10|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-04T05:50:35.7406501+08:00|10|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-04T05:51:05.5885009+08:00|18|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-04T05:51:05.6187569+08:00|18|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: b6756a2fcaa04032a1a358c1f2a9fc24(0-1). 
2022-08-04T05:51:05.6187569+08:00|18|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: b6756a2fcaa04032a1a358c1f2a9fc24(0-1). 
2022-08-04T05:51:07.6731885+08:00|11|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: b6756a2fcaa04032a1a358c1f2a9fc24(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-04T05:51:07.6731885+08:00|11|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: b6756a2fcaa04032a1a358c1f2a9fc24(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-04T05:52:24.4214092+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-04T05:52:24.4457145+08:00|22|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-04T05:52:24.4987861+08:00|22|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-04T05:52:24.5493774+08:00|22|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-04T05:52:24.6007606+08:00|22|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-04T05:52:54.4569804+08:00|11|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-04T05:52:54.4847952+08:00|11|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 123bffeb98c84581989395fdba34334e(0-1). 
2022-08-04T05:52:54.4847952+08:00|11|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 123bffeb98c84581989395fdba34334e(0-1). 
2022-08-04T05:52:56.5278196+08:00|10|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 123bffeb98c84581989395fdba34334e(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-04T05:52:56.5278196+08:00|10|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 123bffeb98c84581989395fdba34334e(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-09T10:33:50.4465339+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-09T10:33:50.4698461+08:00|36|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-09T10:33:50.5234135+08:00|36|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-09T10:33:50.5745032+08:00|36|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-09T10:33:50.6275748+08:00|36|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-09T10:34:20.4814033+08:00|50|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-09T10:34:21.3295631+08:00|50|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 1b8f9772c3c34f4892a11e2441383a50(0-1). 
2022-08-09T10:34:21.3295631+08:00|50|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 1b8f9772c3c34f4892a11e2441383a50(0-1). 
2022-08-09T10:34:21.4510834+08:00|49|INFO|DataSync.Log|TransmissionSent. TransmissionId: 1b8f9772c3c34f4892a11e2441383a50(0-1). Capacity: 0. 
2022-08-09T10:38:55.4538081+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-09T10:38:55.4781133+08:00|54|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-09T10:38:55.5311851+08:00|54|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-09T10:38:55.5822719+08:00|54|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-09T10:38:55.6338564+08:00|54|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-09T10:39:25.4832300+08:00|71|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-09T10:39:25.5129881+08:00|71|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: a1c10644f5924a159255086f07ca75ad(0-1). 
2022-08-09T10:39:25.5129881+08:00|71|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: a1c10644f5924a159255086f07ca75ad(0-1). 
2022-08-09T10:39:25.6002850+08:00|72|INFO|DataSync.Log|TransmissionSent. TransmissionId: a1c10644f5924a159255086f07ca75ad(0-1). Capacity: 0. 
2022-08-09T23:35:22.1522470+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-09T23:35:22.1755583+08:00|105|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-09T23:35:22.2286297+08:00|105|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-09T23:35:22.2797178+08:00|105|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-09T23:35:22.3352698+08:00|105|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-09T23:35:52.1852119+08:00|113|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-09T23:35:52.2144748+08:00|113|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: a432820516bf4356929da73de343559f(0-1). 
2022-08-09T23:35:52.2144748+08:00|113|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: a432820516bf4356929da73de343559f(0-1). 
2022-08-09T23:35:52.3280597+08:00|105|INFO|DataSync.Log|TransmissionSent. TransmissionId: a432820516bf4356929da73de343559f(0-1). Capacity: 0. 
2022-08-09T23:39:20.3657707+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-09T23:39:20.3895788+08:00|106|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-09T23:39:20.4426511+08:00|106|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-09T23:39:20.4937389+08:00|106|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-09T23:39:20.5463151+08:00|106|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-09T23:39:50.3950946+08:00|128|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-09T23:39:50.4253506+08:00|128|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 22da92506f124a54b44a560d620245b8(0-1). 
2022-08-09T23:39:50.4253506+08:00|128|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 22da92506f124a54b44a560d620245b8(0-1). 
2022-08-09T23:39:50.4883435+08:00|113|INFO|DataSync.Log|TransmissionSent. TransmissionId: 22da92506f124a54b44a560d620245b8(0-1). Capacity: 0. 
2022-08-10T00:54:54.3341220+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-10T00:54:54.3594177+08:00|170|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-10T00:54:54.4164577+08:00|170|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-10T00:54:54.4675467+08:00|170|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-10T00:54:54.5191306+08:00|170|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-10T00:55:24.3645723+08:00|180|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-10T00:55:24.3948282+08:00|180|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: d588438e3cdb492bac8af1d07294ec8a(0-1). 
2022-08-10T00:55:24.4057402+08:00|180|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: d588438e3cdb492bac8af1d07294ec8a(0-1). 
2022-08-10T00:55:24.4672443+08:00|170|INFO|DataSync.Log|TransmissionSent. TransmissionId: d588438e3cdb492bac8af1d07294ec8a(0-1). Capacity: 0. 
2022-08-10T01:01:14.5804792+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-10T01:01:14.6037635+08:00|180|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-10T01:01:14.6573315+08:00|180|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-10T01:01:14.7084532+08:00|180|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-10T01:01:14.7614911+08:00|180|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-10T01:01:44.6097753+08:00|179|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-10T01:01:44.6350715+08:00|179|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 1256d04291ae4d32a84a88d8183feca0(0-1). 
2022-08-10T01:01:44.6350715+08:00|179|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 1256d04291ae4d32a84a88d8183feca0(0-1). 
2022-08-10T01:01:44.7020313+08:00|180|INFO|DataSync.Log|TransmissionSent. TransmissionId: 1256d04291ae4d32a84a88d8183feca0(0-1). Capacity: 0. 
2022-08-11T16:55:57.6096162+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-11T16:55:57.6344163+08:00|25|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-11T16:55:57.6879846+08:00|25|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-11T16:55:57.7446152+08:00|25|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-11T16:55:57.8016550+08:00|25|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-11T16:56:27.6456158+08:00|28|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-11T16:56:27.7145594+08:00|28|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 24aac532d0fa42a985be076a47b51835(0-1). 
2022-08-11T16:56:27.7145594+08:00|28|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 24aac532d0fa42a985be076a47b51835(0-1). 
2022-08-11T16:56:27.8737771+08:00|29|INFO|DataSync.Log|TransmissionSent. TransmissionId: 24aac532d0fa42a985be076a47b51835(0-1). Capacity: 0. 
2022-08-11T17:05:32.0827470+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-11T17:05:32.1070518+08:00|56|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-11T17:05:32.1611155+08:00|56|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-11T17:05:32.2117082+08:00|56|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-11T17:05:32.2737065+08:00|56|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-11T17:06:02.1152567+08:00|57|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-11T17:06:02.1445207+08:00|57|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 8eecd206cec642dca91d273d26473c63(0-1). 
2022-08-11T17:06:02.1549369+08:00|57|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 8eecd206cec642dca91d273d26473c63(0-1). 
2022-08-11T17:06:23.2750943+08:00|59|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 8eecd206cec642dca91d273d26473c63(0-1). Message: System.Net.WebException: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ) ---> System.Net.Sockets.SocketException: 連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-11T17:06:23.2750943+08:00|59|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 8eecd206cec642dca91d273d26473c63(0-1). Message: Error: ConnectFailure (連線嘗試失敗，因為連線對象有一段時間並未正確回應，或是連線建立失敗，因為連線的主機無法回應。 ). StatusCode: 0. Description: . 
2022-08-11T17:12:49.2880288+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-11T17:12:49.3123046+08:00|78|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-11T17:12:49.3648805+08:00|78|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-11T17:12:49.4159684+08:00|78|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-11T17:12:49.4700321+08:00|78|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-11T17:13:19.3202776+08:00|81|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-11T17:13:19.3480534+08:00|81|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: b66a5629924d47448da754e2266b3010(0-1). 
2022-08-11T17:13:19.3574776+08:00|81|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: b66a5629924d47448da754e2266b3010(0-1). 
2022-08-11T17:13:19.4348525+08:00|81|INFO|DataSync.Log|TransmissionSent. TransmissionId: b66a5629924d47448da754e2266b3010(0-1). Capacity: 0. 
2022-08-11T17:34:40.0198020+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-11T17:34:40.0446008+08:00|104|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-11T17:34:40.0976741+08:00|104|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-11T17:34:40.1487607+08:00|104|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-11T17:34:40.1998493+08:00|104|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-11T17:35:10.0550538+08:00|105|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-11T17:35:10.0838222+08:00|105|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 3f2753319f2145e0bccd185323b4aab5(0-1). 
2022-08-11T17:35:10.0872938+08:00|105|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 3f2753319f2145e0bccd185323b4aab5(0-1). 
2022-08-11T17:35:10.1855016+08:00|105|INFO|DataSync.Log|TransmissionSent. TransmissionId: 3f2753319f2145e0bccd185323b4aab5(0-1). Capacity: 0. 
2022-08-11T17:42:35.6933986+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-11T17:42:35.7176741+08:00|128|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-11T17:42:35.7717385+08:00|128|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-11T17:42:35.8238182+08:00|128|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-11T17:42:35.8754022+08:00|128|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-11T17:43:05.7258483+08:00|129|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-11T17:43:05.7546159+08:00|129|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: b1cb6749e7e3467d9570bcdd42ff9a4a(0-1). 
2022-08-11T17:43:05.7546159+08:00|129|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: b1cb6749e7e3467d9570bcdd42ff9a4a(0-1). 
2022-08-11T17:43:05.8324889+08:00|129|INFO|DataSync.Log|TransmissionSent. TransmissionId: b1cb6749e7e3467d9570bcdd42ff9a4a(0-1). Capacity: 0. 
2022-08-11T18:15:11.5003418+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-11T18:15:11.5246457+08:00|161|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-11T18:15:11.5787103+08:00|161|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-11T18:15:11.6297973+08:00|161|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-11T18:15:11.6813823+08:00|161|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-11T18:15:41.5324799+08:00|161|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-11T18:15:41.5597584+08:00|161|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 5fe0c43c22254439a874f1437a1ced58(0-1). 
2022-08-11T18:15:41.5597584+08:00|161|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 5fe0c43c22254439a874f1437a1ced58(0-1). 
2022-08-11T18:15:41.6445745+08:00|161|INFO|DataSync.Log|TransmissionSent. TransmissionId: 5fe0c43c22254439a874f1437a1ced58(0-1). Capacity: 0. 
2022-08-11T18:16:03.9058596+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-11T18:16:03.9287034+08:00|162|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-11T18:16:03.9817748+08:00|162|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-11T18:16:04.0328347+08:00|162|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-11T18:16:04.0864029+08:00|162|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-11T18:16:33.9453527+08:00|165|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-11T18:16:33.9736244+08:00|165|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: b3450d0e3ab7452eb1822fa590d3372d(0-1). 
2022-08-11T18:16:33.9736244+08:00|165|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: b3450d0e3ab7452eb1822fa590d3372d(0-1). 
2022-08-11T18:16:34.1075447+08:00|164|INFO|DataSync.Log|TransmissionSent. TransmissionId: b3450d0e3ab7452eb1822fa590d3372d(0-1). Capacity: 0. 
2022-08-11T18:21:11.3719002+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-11T18:21:11.3962034+08:00|196|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-11T18:21:11.4507631+08:00|196|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-11T18:21:11.5018514+08:00|196|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-11T18:21:11.5534355+08:00|196|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-11T18:21:41.4116170+08:00|197|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-11T18:21:41.4413760+08:00|197|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 0a53349c7be847d2a8f1a3feef15219a(0-1). 
2022-08-11T18:21:41.4413760+08:00|197|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 0a53349c7be847d2a8f1a3feef15219a(0-1). 
2022-08-11T18:21:41.5247039+08:00|200|INFO|DataSync.Log|TransmissionSent. TransmissionId: 0a53349c7be847d2a8f1a3feef15219a(0-1). Capacity: 0. 
2022-08-11T18:30:52.8525828+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-11T18:30:52.8763902+08:00|224|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-11T18:30:52.9294627+08:00|224|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-11T18:30:52.9815422+08:00|224|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-11T18:30:53.0331259+08:00|224|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-11T18:31:22.8848583+08:00|225|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-11T18:31:22.9126342+08:00|225|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 2508e7101398406eb7548acf6dc864d0(0-1). 
2022-08-11T18:31:22.9161064+08:00|225|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 2508e7101398406eb7548acf6dc864d0(0-1). 
2022-08-11T18:31:23.0406034+08:00|225|INFO|DataSync.Log|TransmissionSent. TransmissionId: 2508e7101398406eb7548acf6dc864d0(0-1). Capacity: 0. 
2022-08-11T18:53:50.5210793+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-11T18:53:50.5453834+08:00|243|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-11T18:53:50.5984555+08:00|243|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-11T18:53:50.6495443+08:00|243|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-11T18:53:50.7011273+08:00|243|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-11T18:54:20.5583002+08:00|244|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-11T18:54:20.5885565+08:00|244|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 3d2d7bda60154008b9a318217187e159(0-1). 
2022-08-11T18:54:20.5885565+08:00|244|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 3d2d7bda60154008b9a318217187e159(0-1). 
2022-08-11T18:54:20.6718845+08:00|244|INFO|DataSync.Log|TransmissionSent. TransmissionId: 3d2d7bda60154008b9a318217187e159(0-1). Capacity: 0. 
2022-08-11T18:58:59.2643857+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-11T18:58:59.2941469+08:00|269|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-11T18:58:59.3467227+08:00|269|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-11T18:58:59.3997944+08:00|269|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-11T18:58:59.4508827+08:00|269|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-11T18:59:29.3023506+08:00|270|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-11T18:59:29.3301264+08:00|270|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: cdb3db40304c4f45bee362c711ce6996(0-1). 
2022-08-11T18:59:29.3395505+08:00|270|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: cdb3db40304c4f45bee362c711ce6996(0-1). 
2022-08-11T18:59:29.4189102+08:00|270|INFO|DataSync.Log|TransmissionSent. TransmissionId: cdb3db40304c4f45bee362c711ce6996(0-1). Capacity: 0. 
2022-08-11T19:05:10.2444391+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-11T19:05:10.2687421+08:00|293|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-11T19:05:10.3218155+08:00|293|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-11T19:05:10.3778632+08:00|293|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-11T19:05:10.4289513+08:00|293|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-11T19:05:40.2860897+08:00|294|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-11T19:05:40.3148582+08:00|294|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: ca7f5378ec4d4cb0abfe37e39ac5da64(0-1). 
2022-08-11T19:05:40.3148582+08:00|294|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: ca7f5378ec4d4cb0abfe37e39ac5da64(0-1). 
2022-08-11T19:05:40.4562172+08:00|297|INFO|DataSync.Log|TransmissionSent. TransmissionId: ca7f5378ec4d4cb0abfe37e39ac5da64(0-1). Capacity: 0. 
2022-08-17T01:40:52.2698887+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-17T01:40:52.2946887+08:00|317|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-17T01:40:52.3477602+08:00|317|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-17T01:40:52.3988491+08:00|317|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-17T01:40:52.4509279+08:00|317|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-17T01:41:22.3119518+08:00|318|INFO|DataSync.Log|SerializationStarted. Items count: 3 
2022-08-17T01:41:22.3357598+08:00|318|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 680c8d445bf74e92ae3241f3ea11a7ff(0-2). 
2022-08-17T01:41:22.3357598+08:00|318|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 680c8d445bf74e92ae3241f3ea11a7ff(0-2). 
2022-08-17T01:41:24.4511879+08:00|327|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 680c8d445bf74e92ae3241f3ea11a7ff(0-2). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-17T01:41:24.4511879+08:00|327|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 680c8d445bf74e92ae3241f3ea11a7ff(0-2). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-17T12:20:23.9951419+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-17T12:20:24.0219272+08:00|349|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-17T12:20:24.0749988+08:00|349|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-17T12:20:24.1265816+08:00|349|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-17T12:20:24.1786624+08:00|349|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-17T12:20:54.0279577+08:00|349|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-17T12:20:54.0582142+08:00|349|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 938f2b2b6a2547f7940abf2146760300(0-1). 
2022-08-17T12:20:54.0582142+08:00|349|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 938f2b2b6a2547f7940abf2146760300(0-1). 
2022-08-17T12:20:56.1776196+08:00|360|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 938f2b2b6a2547f7940abf2146760300(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-17T12:20:56.1800999+08:00|360|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 938f2b2b6a2547f7940abf2146760300(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-17T12:26:23.2391039+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-17T12:26:23.2653921+08:00|372|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-17T12:26:23.3189600+08:00|372|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-17T12:26:23.3700478+08:00|372|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-17T12:26:23.4290719+08:00|372|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-17T12:26:53.2788207+08:00|378|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-17T12:26:53.3085809+08:00|378|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 65468a3e552343a3917a824df4bb74a6(0-1). 
2022-08-17T12:26:53.3239568+08:00|378|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 65468a3e552343a3917a824df4bb74a6(0-1). 
2022-08-17T12:26:55.3768988+08:00|388|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 65468a3e552343a3917a824df4bb74a6(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-17T12:26:55.3902907+08:00|388|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 65468a3e552343a3917a824df4bb74a6(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-18T15:30:19.0040973+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-18T15:30:19.0485629+08:00|410|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-18T15:30:19.1027167+08:00|410|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-18T15:30:19.1534340+08:00|410|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-18T15:30:19.2052175+08:00|410|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-18T15:30:49.4895019+08:00|411|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-18T15:30:49.5207496+08:00|411|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: d3dba269d9674d15b78ab7e2fa918f51(0-1). 
2022-08-18T15:30:51.7503138+08:00|411|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: d3dba269d9674d15b78ab7e2fa918f51(0-1). 
2022-08-18T15:30:54.6034536+08:00|413|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: d3dba269d9674d15b78ab7e2fa918f51(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-18T15:30:54.6034536+08:00|413|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: d3dba269d9674d15b78ab7e2fa918f51(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-18T15:42:21.6748969+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-18T15:42:21.6987050+08:00|445|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-18T15:42:21.7567351+08:00|445|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-18T15:42:21.8078231+08:00|445|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-18T15:42:21.8594070+08:00|445|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-18T15:42:51.7035383+08:00|446|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-18T15:42:51.7323064+08:00|446|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: cdf51184cb9245bba317ff7ec762f342(0-1). 
2022-08-18T15:42:51.7422259+08:00|446|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: cdf51184cb9245bba317ff7ec762f342(0-1). 
2022-08-18T15:42:53.7907792+08:00|453|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: cdf51184cb9245bba317ff7ec762f342(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-18T15:42:53.7907792+08:00|453|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: cdf51184cb9245bba317ff7ec762f342(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-21T18:00:02.7852922+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-21T18:00:02.8081073+08:00|14|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-21T18:00:02.8611789+08:00|14|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-21T18:00:02.9137546+08:00|14|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-21T18:00:02.9648431+08:00|14|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-21T18:00:32.8294553+08:00|9|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-21T18:00:32.8562394+08:00|9|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 079b9190829e4f66b81c71181818e6cf(0-1). 
2022-08-21T18:00:32.8562394+08:00|9|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 079b9190829e4f66b81c71181818e6cf(0-1). 
2022-08-21T18:00:34.9627482+08:00|11|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 079b9190829e4f66b81c71181818e6cf(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-21T18:00:34.9627482+08:00|11|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 079b9190829e4f66b81c71181818e6cf(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-23T15:45:05.2876890+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-23T15:45:05.3101887+08:00|16|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-23T15:45:05.3632607+08:00|16|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-23T15:45:05.4143487+08:00|16|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-23T15:45:05.4689084+08:00|16|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-23T15:45:35.3213155+08:00|9|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-23T15:45:35.3833150+08:00|9|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 7927d2ee442743f8bb7f413b3e987eaf(0-1). 
2022-08-23T15:45:35.3833150+08:00|9|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 7927d2ee442743f8bb7f413b3e987eaf(0-1). 
2022-08-23T15:45:37.5245445+08:00|10|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 7927d2ee442743f8bb7f413b3e987eaf(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-23T15:45:37.5245445+08:00|10|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 7927d2ee442743f8bb7f413b3e987eaf(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-23T16:37:41.4345576+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-23T16:37:41.4628289+08:00|10|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-23T16:37:41.5163971+08:00|10|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-23T16:37:41.5669891+08:00|10|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-23T16:37:41.6200608+08:00|10|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-23T16:38:11.4729052+08:00|12|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-23T16:38:11.4991938+08:00|12|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 492be9255ebc423d8aed8c82ac1bae61(0-1). 
2022-08-23T16:38:11.4991938+08:00|12|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 492be9255ebc423d8aed8c82ac1bae61(0-1). 
2022-08-23T16:38:13.5520897+08:00|9|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 492be9255ebc423d8aed8c82ac1bae61(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-23T16:38:13.5545694+08:00|9|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 492be9255ebc423d8aed8c82ac1bae61(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-23T18:27:12.7724513+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-23T18:27:12.7942754+08:00|86|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-23T18:27:12.8483400+08:00|86|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-23T18:27:12.9019069+08:00|86|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-23T18:27:12.9544830+08:00|86|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-23T18:27:42.8034982+08:00|16|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-23T18:27:42.8322651+08:00|16|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: c76dfcd1d9ee40c2a6f7c85513067a28(0-1). 
2022-08-23T18:27:42.8347449+08:00|16|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: c76dfcd1d9ee40c2a6f7c85513067a28(0-1). 
2022-08-23T18:27:44.8817362+08:00|10|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: c76dfcd1d9ee40c2a6f7c85513067a28(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-23T18:27:44.8817362+08:00|10|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: c76dfcd1d9ee40c2a6f7c85513067a28(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T09:53:56.7039334+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-24T09:53:56.7232772+08:00|86|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-24T09:53:56.7778653+08:00|86|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-24T09:53:56.8289253+08:00|86|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-24T09:53:56.8805373+08:00|86|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-24T09:54:26.7307537+08:00|128|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-24T09:54:26.7654732+08:00|128|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 19f192d4eabb4ad3b268de239a4f1e48(0-1). 
2022-08-24T09:54:26.7654732+08:00|128|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 19f192d4eabb4ad3b268de239a4f1e48(0-1). 
2022-08-24T09:54:28.8685110+08:00|86|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 19f192d4eabb4ad3b268de239a4f1e48(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T09:54:28.8685110+08:00|86|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 19f192d4eabb4ad3b268de239a4f1e48(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T10:02:20.7825609+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-24T10:02:20.8043855+08:00|14|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-24T10:02:20.8625469+08:00|14|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-24T10:02:20.9136346+08:00|14|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-24T10:02:20.9652175+08:00|14|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-24T10:02:50.8110330+08:00|13|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-24T10:02:50.8412883+08:00|13|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 8adfb146f0694cb9bb034bc5609fdb47(0-1). 
2022-08-24T10:02:50.8412883+08:00|13|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 8adfb146f0694cb9bb034bc5609fdb47(0-1). 
2022-08-24T10:02:52.8927423+08:00|16|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 8adfb146f0694cb9bb034bc5609fdb47(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T10:02:52.8927423+08:00|16|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 8adfb146f0694cb9bb034bc5609fdb47(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T10:08:09.0909595+08:00|1|INFO|DataSync.Log|Transmitter flushed telemetry events. 
2022-08-24T10:08:09.0909595+08:00|1|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2022-08-24T10:08:09.0909595+08:00|1|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 3fa0035909624c50b9a37bfbe9a7e7d3(2-2). 
2022-08-24T10:08:09.0909595+08:00|1|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 3fa0035909624c50b9a37bfbe9a7e7d3(2-2). 
2022-08-24T10:08:09.0909595+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed sender capacity to 0 
2022-08-24T10:08:09.0909595+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed buffer capacity to 0 
2022-08-24T10:08:09.0909595+08:00|1|INFO|DataSync.Log|StorageCapacityReset: DataSync.ApplicationLifecycleTransmissionPolicy 
2022-08-24T10:08:09.0909595+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2022-08-24T10:08:09.0909595+08:00|1|INFO|DataSync.Log|MovedFromBufferToStorage. 
2022-08-24T10:08:09.0909595+08:00|1|INFO|DataSync.Log|TransmitterEmptyBuffer 
2022-08-24T10:08:09.1003834+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2022-08-24T10:08:11.1245572+08:00|86|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 3fa0035909624c50b9a37bfbe9a7e7d3(2-2). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T10:08:11.1245572+08:00|86|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 3fa0035909624c50b9a37bfbe9a7e7d3(2-2). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T10:08:11.1245572+08:00|86|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 0. Capacity: 0. 
2022-08-24T10:09:30.1043954+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-24T10:09:30.1277354+08:00|10|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-24T10:09:30.1807797+08:00|10|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-24T10:09:30.2318676+08:00|10|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-24T10:09:30.2829556+08:00|10|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-24T10:10:00.1341910+08:00|11|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-24T10:10:00.1674232+08:00|11|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: f74e020aa7054500ad6ac29518c93fe8(0-1). 
2022-08-24T10:10:00.1674232+08:00|11|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: f74e020aa7054500ad6ac29518c93fe8(0-1). 
2022-08-24T10:10:02.2203659+08:00|13|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: f74e020aa7054500ad6ac29518c93fe8(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T10:10:02.2203659+08:00|13|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: f74e020aa7054500ad6ac29518c93fe8(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T10:14:54.2509714+08:00|1|INFO|DataSync.Log|Transmitter flushed telemetry events. 
2022-08-24T10:14:54.2509714+08:00|1|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2022-08-24T10:14:54.2509714+08:00|1|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 896a1f5aebac48699aeb4fb7fe6478bc(2-2). 
2022-08-24T10:14:54.2509714+08:00|1|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 896a1f5aebac48699aeb4fb7fe6478bc(2-2). 
2022-08-24T10:14:54.2569234+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed sender capacity to 0 
2022-08-24T10:14:54.2569234+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed buffer capacity to 0 
2022-08-24T10:14:54.2569234+08:00|1|INFO|DataSync.Log|StorageCapacityReset: DataSync.ApplicationLifecycleTransmissionPolicy 
2022-08-24T10:14:54.2569234+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2022-08-24T10:14:54.2569234+08:00|1|INFO|DataSync.Log|MovedFromBufferToStorage. 
2022-08-24T10:14:54.2569234+08:00|1|INFO|DataSync.Log|TransmitterEmptyBuffer 
2022-08-24T10:14:54.2569234+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2022-08-24T10:14:56.2967938+08:00|11|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 896a1f5aebac48699aeb4fb7fe6478bc(2-2). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T10:14:56.2967938+08:00|11|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 896a1f5aebac48699aeb4fb7fe6478bc(2-2). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T10:14:56.2967938+08:00|11|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 0. Capacity: 0. 
2022-08-24T10:18:12.0691832+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-24T10:18:12.0900150+08:00|13|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-24T10:18:12.1430878+08:00|13|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-24T10:18:12.1941745+08:00|13|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-24T10:18:12.2457604+08:00|13|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-24T10:18:42.0971395+08:00|14|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-24T10:18:42.1234275+08:00|14|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 5144754ab807471297628f62c38a9ba4(0-1). 
2022-08-24T10:18:42.1234275+08:00|14|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 5144754ab807471297628f62c38a9ba4(0-1). 
2022-08-24T10:18:44.1823218+08:00|15|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 5144754ab807471297628f62c38a9ba4(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T10:18:44.1823218+08:00|15|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 5144754ab807471297628f62c38a9ba4(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T10:23:51.8007385+08:00|1|INFO|DataSync.Log|Transmitter flushed telemetry events. 
2022-08-24T10:23:51.8007385+08:00|1|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2022-08-24T10:23:51.8047075+08:00|1|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: e7ecd797a6114b7183d3a22f938d057e(2-2). 
2022-08-24T10:23:51.8047075+08:00|1|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: e7ecd797a6114b7183d3a22f938d057e(2-2). 
2022-08-24T10:23:51.8047075+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed sender capacity to 0 
2022-08-24T10:23:51.8047075+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed buffer capacity to 0 
2022-08-24T10:23:51.8047075+08:00|1|INFO|DataSync.Log|StorageCapacityReset: DataSync.ApplicationLifecycleTransmissionPolicy 
2022-08-24T10:23:51.8047075+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2022-08-24T10:23:51.8047075+08:00|1|INFO|DataSync.Log|MovedFromBufferToStorage. 
2022-08-24T10:23:51.8047075+08:00|1|INFO|DataSync.Log|TransmitterEmptyBuffer 
2022-08-24T10:23:51.8047075+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2022-08-24T10:23:53.8333460+08:00|172|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: e7ecd797a6114b7183d3a22f938d057e(2-2). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T10:23:53.8333460+08:00|172|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: e7ecd797a6114b7183d3a22f938d057e(2-2). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T10:23:53.8353298+08:00|172|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 0. Capacity: 0. 
2022-08-24T10:26:55.6509051+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-24T10:26:55.6509051+08:00|13|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-24T10:26:55.7034808+08:00|13|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-24T10:26:55.7540732+08:00|13|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-24T10:26:55.8046643+08:00|13|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-24T10:27:25.6528334+08:00|16|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-24T10:27:25.6528334+08:00|16|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: fd8ff5ba7c354dca948dc90c1598161c(0-1). 
2022-08-24T10:27:25.6528334+08:00|16|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: fd8ff5ba7c354dca948dc90c1598161c(0-1). 
2022-08-24T10:27:27.6829596+08:00|15|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: fd8ff5ba7c354dca948dc90c1598161c(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T10:27:27.6829596+08:00|15|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: fd8ff5ba7c354dca948dc90c1598161c(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T10:36:02.6830932+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-24T10:36:02.7044223+08:00|13|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-24T10:36:02.7574941+08:00|13|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-24T10:36:02.8085814+08:00|13|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-24T10:36:02.8601935+08:00|13|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-24T10:36:32.7119013+08:00|173|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-24T10:36:32.7342210+08:00|173|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 7a1b9c99dd4a42bfad965a1506012abe(0-1). 
2022-08-24T10:36:32.7342210+08:00|173|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 7a1b9c99dd4a42bfad965a1506012abe(0-1). 
2022-08-24T10:36:34.7836926+08:00|13|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 7a1b9c99dd4a42bfad965a1506012abe(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T10:36:34.7836926+08:00|13|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 7a1b9c99dd4a42bfad965a1506012abe(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T10:41:46.0679198+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-24T10:41:46.0902394+08:00|13|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-24T10:41:46.1438086+08:00|13|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-24T10:41:46.1948950+08:00|13|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-24T10:41:46.2459830+08:00|13|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-24T10:42:26.8286154+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-24T10:42:26.8494478+08:00|128|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-24T10:42:26.9025190+08:00|128|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-24T10:42:26.9536077+08:00|128|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-24T10:42:27.0052191+08:00|128|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-24T10:42:56.8559315+08:00|16|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-24T10:42:56.8802355+08:00|16|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: de0773b8e75f4f859ee06964980b5b3e(0-1). 
2022-08-24T10:42:56.8827153+08:00|16|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: de0773b8e75f4f859ee06964980b5b3e(0-1). 
2022-08-24T10:42:58.9430972+08:00|191|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: de0773b8e75f4f859ee06964980b5b3e(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T10:42:58.9460732+08:00|191|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: de0773b8e75f4f859ee06964980b5b3e(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T10:51:09.4450876+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-24T10:51:09.4674076+08:00|14|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-24T10:51:09.5199835+08:00|14|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-24T10:51:09.5710721+08:00|14|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-24T10:51:09.6236470+08:00|14|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-24T10:51:39.4745003+08:00|173|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-24T10:51:39.4988042+08:00|173|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: cc655d4b551e45c68107a4b427c12185(0-1). 
2022-08-24T10:51:39.4988042+08:00|173|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: cc655d4b551e45c68107a4b427c12185(0-1). 
2022-08-24T10:51:41.5443071+08:00|14|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: cc655d4b551e45c68107a4b427c12185(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T10:51:41.5443071+08:00|14|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: cc655d4b551e45c68107a4b427c12185(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T11:04:45.9374166+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-24T11:04:45.9587439+08:00|256|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-24T11:04:46.0123128+08:00|256|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-24T11:04:46.0634009+08:00|256|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-24T11:04:46.1149834+08:00|256|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-24T11:05:15.9652279+08:00|257|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-24T11:05:15.9905239+08:00|257|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: e127152ad16342faaf026c40d662dfce(0-1). 
2022-08-24T11:05:15.9935000+08:00|257|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: e127152ad16342faaf026c40d662dfce(0-1). 
2022-08-24T11:05:18.0479298+08:00|191|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: e127152ad16342faaf026c40d662dfce(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T11:05:18.0479298+08:00|191|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: e127152ad16342faaf026c40d662dfce(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T11:07:40.3551735+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-24T11:07:40.3765018+08:00|16|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-24T11:07:40.4295729+08:00|16|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-24T11:07:40.4806616+08:00|16|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-24T11:07:40.5317498+08:00|16|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-24T11:08:10.3824891+08:00|86|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-24T11:08:10.4162170+08:00|86|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 10f39d165722408798eea39a9e3d31f1(0-1). 
2022-08-24T11:08:10.4162170+08:00|86|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 10f39d165722408798eea39a9e3d31f1(0-1). 
2022-08-24T11:08:12.4780875+08:00|258|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 10f39d165722408798eea39a9e3d31f1(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T11:08:12.4780875+08:00|258|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 10f39d165722408798eea39a9e3d31f1(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T11:12:35.0608220+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-24T11:12:35.0831412+08:00|191|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-24T11:12:35.1362140+08:00|191|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-24T11:12:35.1873018+08:00|191|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-24T11:12:35.2398769+08:00|191|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-24T11:13:05.0896260+08:00|16|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-24T11:13:05.1223614+08:00|16|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 44484ab46bf0484bb3bb292b6e1ff598(0-1). 
2022-08-24T11:13:05.1223614+08:00|16|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 44484ab46bf0484bb3bb292b6e1ff598(0-1). 
2022-08-24T11:13:07.1728239+08:00|258|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 44484ab46bf0484bb3bb292b6e1ff598(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T11:13:07.1728239+08:00|258|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 44484ab46bf0484bb3bb292b6e1ff598(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T11:20:49.5781791+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-24T11:20:49.6009963+08:00|237|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-24T11:20:49.6540670+08:00|237|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-24T11:20:49.7051554+08:00|237|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-24T11:20:49.7577303+08:00|237|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-24T11:21:19.6069825+08:00|248|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-24T11:21:19.6322786+08:00|248|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 815938aecf3845a4a5cf6ebf58cc7bc3(0-1). 
2022-08-24T11:21:19.6322786+08:00|248|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 815938aecf3845a4a5cf6ebf58cc7bc3(0-1). 
2022-08-24T11:21:21.6847257+08:00|256|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 815938aecf3845a4a5cf6ebf58cc7bc3(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T11:21:21.6847257+08:00|256|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 815938aecf3845a4a5cf6ebf58cc7bc3(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T11:22:18.0599815+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-24T11:22:18.0818057+08:00|256|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-24T11:22:18.1348770+08:00|256|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-24T11:22:18.1859657+08:00|256|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-24T11:22:18.2370534+08:00|256|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-24T11:22:48.0890116+08:00|237|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-24T11:22:48.1157952+08:00|237|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: bf842e8c8c0d472a8419ff353b339440(0-1). 
2022-08-24T11:22:48.1187719+08:00|237|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: bf842e8c8c0d472a8419ff353b339440(0-1). 
2022-08-24T11:22:50.1771697+08:00|173|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: bf842e8c8c0d472a8419ff353b339440(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T11:22:50.1801452+08:00|173|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: bf842e8c8c0d472a8419ff353b339440(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T11:31:21.6372152+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-24T11:31:21.6585429+08:00|191|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-24T11:31:21.7116147+08:00|191|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-24T11:31:21.7627334+08:00|191|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-24T11:31:21.8142871+08:00|191|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-24T11:31:51.6759389+08:00|248|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-24T11:31:51.7012350+08:00|248|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: ee0840cd62ac432fa4bec9ed87e61180(0-1). 
2022-08-24T11:31:51.7012350+08:00|248|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: ee0840cd62ac432fa4bec9ed87e61180(0-1). 
2022-08-24T11:31:53.7521934+08:00|86|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: ee0840cd62ac432fa4bec9ed87e61180(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T11:31:53.7521934+08:00|86|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: ee0840cd62ac432fa4bec9ed87e61180(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T11:37:48.2594305+08:00|1|INFO|DataSync.Log|Transmitter flushed telemetry events. 
2022-08-24T11:37:48.2594305+08:00|1|INFO|DataSync.Log|SerializationStarted. Items count: 1 
2022-08-24T11:37:48.2594305+08:00|1|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: 05331a4d6865465a8a6b04da9902c4e0(2-2). 
2022-08-24T11:37:48.2594305+08:00|1|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: 05331a4d6865465a8a6b04da9902c4e0(2-2). 
2022-08-24T11:37:48.2594305+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed sender capacity to 0 
2022-08-24T11:37:48.2594305+08:00|1|INFO|DataSync.Log|DataSync.ApplicationLifecycleTransmissionPolicy changed buffer capacity to 0 
2022-08-24T11:37:48.2594305+08:00|1|INFO|DataSync.Log|StorageCapacityReset: DataSync.ApplicationLifecycleTransmissionPolicy 
2022-08-24T11:37:48.2594305+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2022-08-24T11:37:48.2594305+08:00|1|INFO|DataSync.Log|MovedFromBufferToStorage. 
2022-08-24T11:37:48.2594305+08:00|1|INFO|DataSync.Log|TransmitterEmptyBuffer 
2022-08-24T11:37:48.2594305+08:00|1|WARN|DataSync.Log|BufferEnqueueNoCapacity. Size: 0. Capacity: 0. 
2022-08-24T11:37:50.2991083+08:00|191|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 05331a4d6865465a8a6b04da9902c4e0(2-2). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T11:37:50.2991083+08:00|191|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: 05331a4d6865465a8a6b04da9902c4e0(2-2). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-24T11:37:50.2991083+08:00|191|WARN|DataSync.Log|SenderEnqueueNoCapacity. TransmissionCount: 0. Capacity: 0. 
2022-08-24T12:26:36.0191195+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-24T12:26:36.0404474+08:00|339|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-24T12:26:36.0940153+08:00|339|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-24T12:26:36.1451039+08:00|339|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-24T12:26:36.1966874+08:00|339|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-24T12:27:06.0477117+08:00|86|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-24T12:27:06.0700324+08:00|86|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: eff455c3c04840d89eca40acd70c0cf1(0-1). 
2022-08-24T12:27:06.0700324+08:00|86|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: eff455c3c04840d89eca40acd70c0cf1(0-1). 
2022-08-24T12:27:08.1343815+08:00|256|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: eff455c3c04840d89eca40acd70c0cf1(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-24T12:27:08.1343815+08:00|256|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: eff455c3c04840d89eca40acd70c0cf1(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-25T17:06:20.6232676+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-25T17:06:20.6436035+08:00|383|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-25T17:06:20.6966759+08:00|383|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-25T17:06:20.7477637+08:00|383|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-25T17:06:20.7993479+08:00|383|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-25T17:06:50.6506913+08:00|256|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-25T17:06:50.6720187+08:00|256|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: d8fb6548711249068f0637dc387a06f2(0-1). 
2022-08-25T17:06:50.6720187+08:00|256|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: d8fb6548711249068f0637dc387a06f2(0-1). 
2022-08-25T17:06:52.7626579+08:00|342|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: d8fb6548711249068f0637dc387a06f2(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-25T17:06:52.7626579+08:00|342|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: d8fb6548711249068f0637dc387a06f2(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
2022-08-25T17:15:25.4375457+08:00|1|INFO|DataSync.Log|Storage folder: C:\Users\wmlab\Desktop\堆積木遊戲\cubeGame\Assets\TestData\TestStore successfully validated. 
2022-08-25T17:15:25.4588740+08:00|191|INFO|DataSync.Log|StorageSize. StorageSize: 0. 
2022-08-25T17:15:25.5119458+08:00|191|INFO|DataSync.Log|MovedFromStorageToSender. 
2022-08-25T17:15:25.5630333+08:00|191|INFO|DataSync.Log|MovedFromStorageToBuffer. 
2022-08-25T17:15:25.6146172+08:00|191|INFO|DataSync.Log|MovedFromBufferToSender. 
2022-08-25T17:15:55.4707070+08:00|173|INFO|DataSync.Log|SerializationStarted. Items count: 2 
2022-08-25T17:15:55.4875719+08:00|173|INFO|DataSync.Log|TransmitterEnqueue. TransmissionId: b048077e07c04db08547a411f8029264(0-1). 
2022-08-25T17:15:55.4875719+08:00|173|INFO|DataSync.Log|TransmissionSendStarted. TransmissionId: b048077e07c04db08547a411f8029264(0-1). 
2022-08-25T17:15:57.5485194+08:00|342|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: b048077e07c04db08547a411f8029264(0-1). Message: System.Net.WebException: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ) ---> System.Net.Sockets.SocketException: 無法連線，因為目標電腦拒絕連線。    at System.Net.Sockets.Socket.Connect (System.Net.EndPoint remoteEP) [0x000b6] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Net.WebConnection.Connect (System.Net.HttpWebRequest request) [0x0016d] in <735c83e43c004ee998f77c68cf8035da>:0     --- End of inner exception stack trace ---   at System.Net.HttpWebRequest.EndGetRequestStream (System.IAsyncResult asyncResult) [0x0003a] in <735c83e43c004ee998f77c68cf8035da>:0    at System.Threading.Tasks.TaskFactory`1[TResult].FromAsyncCoreLogic (System.IAsyncResult iar, System.Func`2[T,TResult] endFunction, System.Action`1[T] endAction, System.Threading.Tasks.Task`1[TResult] promise, System.Boolean requiresSynchronization) [0x0000f] in <599589bf4ce248909b8a14cbe4a2034e>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<GetResponseAsync>d__39.MoveNext () [0x00086] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.Channel.Transmission+<SendAsync>d__36.MoveNext () [0x0017d] in <20f93252061247f09e8451bed298b761>:0  --- End of stack trace from previous location where exception was thrown ---   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <599589bf4ce248909b8a14cbe4a2034e>:0    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1+ConfiguredTaskAwaiter[TResult].GetResult () [0x00000] in <599589bf4ce248909b8a14cbe4a2034e>:0    at DataSync.TransmissionSender+<StartSending>d__24.MoveNext () [0x000bb] in <20f93252061247f09e8451bed298b761>:0 . 
2022-08-25T17:15:57.5485194+08:00|342|WARN|DataSync.Log|TransmissionSendingFailed. TransmissionId: b048077e07c04db08547a411f8029264(0-1). Message: Error: ConnectFailure (無法連線，因為目標電腦拒絕連線。 ). StatusCode: 0. Description: . 
